services:
  gesttech:
    build:
      context: .
      no_cache: true
      pull: true
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    pull_policy: build

networks:
  pi_default:
    external: true
