# Generated by Django 5.1 on 2024-08-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_addres', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
